### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Holdmyhand** [kingsollyu/AppEnv#5]
能否增加ro.product.name=
ro.product.device=
这两项的修改

**Comment by kingsollyu** [comment]
有的

**Comment by Holdmyhand** [comment]
感谢回复
ro.product.manufacturer=
ro.product.model=
机型修改里面的是这两项。

ro.product.name=
ro.product.device=这两项在哪儿啊

**Comment by kingsollyu** [comment]
代码里写的，界面没有展现，具体关系是这样的
ro.product.name=ro.product.model
ro.product.device=ro.product.model

**Comment by Holdmyhand** [comment]
呀 等等ro.product.name=
ro.product.device=这两项是机型代号，直接改为机型好像没用。

**Comment by Holdmyhand** [comment]
我是想用这个伪装支持daydream vr的机型，看了面具里面开启daydream的模块里面修改了ro.product.name=
ro.product.device=这两项为谷歌手机的机型代号marlin。测试了下让daydream生效的就是这两项。但是面具修改后手机机型就变了就不能OTA了，所以想用这个伪装机型。

**Comment by kingsollyu** [comment]
具体能不能拦截、伪装还是要看这个软件对xposed有没有对抗，正常没有对抗的是可以拦截的。

**Comment by Holdmyhand** [comment]
好的，非常感谢答复
