### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [kingsollyu/AppEnv#7]
本地`gradlew assembleRelease`编译后，生成安装包无法安装。提示-102错误"Couldn't parse installation package"。
[com.sollyu.xposed.hook.model-release-v3.2.0-582-official-20190121.zip](https://github.com/kingsollyu/AppEnv/files/2780081/com.sollyu.xposed.hook.model-release-v3.2.0-582-official-20190121.zip)
使用`gradlew assembleDebug`生成的apk可以安装，但是进入后就一直处于加载中无法操作。
[com.sollyu.xposed.hook.model-debug-v3.2.0-582-official-20190121.zip](https://github.com/kingsollyu/AppEnv/files/2780082/com.sollyu.xposed.hook.model-debug-v3.2.0-582-official-20190121.zip)
![default](https://user-images.githubusercontent.com/32661032/51492425-bf457b80-1dec-11e9-9578-16977552227a.png)
另外，编译出的大小相比酷安上能下载到的小了一倍，版本也落后。

**Comment by kingsollyu** [comment]
这里的代码少了Kotlin
